"""empty message

Revision ID: 1139307bc188
Revises: 73a179bf2f7e
Create Date: 2025-01-04 14:31:30.114293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1139307bc188'
down_revision = '73a179bf2f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint('folder_subject_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint('note_folder_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'folder', ['folder_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('note_folder_id_fkey', 'folder', ['folder_id'], ['id'])

    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('folder_subject_id_fkey', 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###
