name: Study Buddy Backend CI

on:
  push:
    branches: [ "live" ]

jobs:
  deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: zeus1999 # ${{ secrets.DOCKERHUB_USERNAME }}
                password: dckr_pat_jJqLJAYTdbaX7Ppd5_T85_lDKG8 # ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: "{{defaultContext}}:studyBuddyBackend"
                push: true
                tags: zeus1999/studybuddybackend:latest
            - name: Trigger deployment
              run: curl https://api.render.com/deploy/srv-cslun7hu0jms73b9b310?key=bF4pVt9Udz8
